### ISSUE TITLE
Plugin status

### ISSUE THREAD

**Issue by miroi** [darrencocco/moodle-atto_drawing#1]
Dear Daren,

As teacher, I am searching for free Moodle 3.x drawing plugin. The PoodLL plugin is charged now (from version 3) .

I found your post https://moodle.org/mod/forum/discuss.php?d=305414 and this github repository.

Please what is the status of this plugin ? Will it work when I try to install for Moodle 3.x ?

**Comment by darrencocco** [comment]
It should work AFAIK. Development has stopped because my employer de-prioritised it.

**Comment by darrencocco** [comment]
If there is interest I am happy to throw a bit of personal time into developing it and making it more comprehensive but for now it will staya as is.

**Comment by miroi** [comment]
Dear Daren,

I checked you plugin with our (testing) Moodle 3.1. It installed well, but after inserting it into atto toolbar config :
~~~
files = **racsdrawing**, image, media, managefiles 
~~~

the drawing button is not showing up in the Atto editor.

Concerning interest, I (as university teacher) am interested in atto drawing tool, as I need that my students draw chemical structures, reactions etc during online exams.

**Comment by darrencocco** [comment]
I will take a look when I have some time over the next couple of days.

**Comment by miroi** [comment]
Any progress in this topic, please ?

**Comment by darrencocco** [comment]
Unfortunately due to my job responsibilities I have been unable to work on this project. You will have to consider it dead for all intents and purposes for the time being. I may pick up on it in the future but that is unlikely to meet any of your time lines.
